### PR TITLE
Nugget info tab

### PR DESCRIPTION
**Pull request by mattlub**
#27 

This what it looks like, opinions please.
I quite like the fonts.
I don't really like the 'x' button but **I don't think it's that important right now**

screen shot 2017-05-04 at 14 36 13

### CODE REVIEW

**Review by HilbertSpitzer — APPROVED** [review]

**Comment by Suuuuha** [comment]
i think the "submitted by ..." line with the date could be smaller maybe but other than that looks good .. **for now** ;)

**Review by Suuuuha — APPROVED** [review]

**Comment by Karyum** [comment]
the image doesn't look that good maybe it should be bigger so that the user could see better and wouldn't look  bad on the tab

**Comment by Karyum** [comment]
and i actually quite like the x button i think we should :shipit:

**Comment by mattlub** [comment]
@Suuuuha 
Agree, the text could be smaller.

@Karyum 
my issue with the 'x' button is that's it's way too bold- I might look for a thinner one if I get the time.
The image, yeh maybe I'll make it a bit bigger, and round the edges a little bit?
I haven't thought about what happens if the submitted image is not a square, we need to deal with this...

@all Also, are we having likes or not, I want to put them in ;)

**Comment by mattlub** [comment]
New changes to image and font size of author 

looks pretty buff now imho ;)

screen shot 2017-05-04 at 15 13 08

**Comment by Karyum** [comment]
@mattlub in my opinion we don't need likes right now 
and about the image, i guess you would use something responsive so depending on the image size and how its shaped it would render it to the info tab the way it is 
round edges sounds good :shipit:

**Pull request merged**
